AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Lambda function for DMS alarm"

Globals:
  Function:
    Timeout: 3

Resources:
  DmsAlarmFunction:
    Type: AWS::Serverless::Function
    Properties:
#      CodeUri: dms_lambda/
#      CodeUri: s3://20200513mysambucket/myCode.zip
      CodeUri: s3://20200513mysambucket/myCode.zip
      Handler: app.lambda_handler
      Runtime: python3.8
      FunctionName: 'DmsFunction'
      Events:
        LogGroupEvent:
          Type: CloudWatchLogs
          Properties:
            FilterPattern: 'END'
            LogGroupName: '/aws/lambda/basicPython'

  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Schedule for triggering DMS tasks"
      EventBusName: "default"
      Name: "dmsScheduleEventBridgeRule"
      ScheduleExpression: "rate(1 minute)"
      State: 'ENABLED'
      Targets:
        - Arn: !GetAtt DmsAlarmFunction.Arn
          Id: "LambdaFunction"
          Input: "{\"DmsTaskName\": \"DmsTask1\"}"


  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DmsAlarmFunction
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt EventRule.Arn


Outputs:
  DmsAlarmFunction:
    Description: "DMS alarm Lambda Function ARN"
    Value: !GetAtt DmsAlarmFunction.Arn